locationsList = \
    ["Abbotsford, BC",
    "Akulivik, QC",
    "Aldershot, ON – Rail service",
    "Alexandria,ON – Rail service",
    "Alma, QC",
    "Anahim Lake, BC",
    "Angling Lake, ON",
    "Arctic Bay, NU",
    "Arviat, NU",
    "Attawapiskat, ON",
    "Aupaluk, QC",
    "Bagotville, QC",
    "Baie Comeau, QC",
    "Baker Lake, NU",
    "Bathhurst, NB",
    "Bearskin Lake, ON",
    "Bella Bella, BC",
    "Bella Coola, BC",
    "Belleville, ON – Rail service",
    "Berens River, MB",
    "Big Trout, ON",
    "Black Tickle, NL",
    "Blanc Sablon, QC",
    "Bonaventure, QC",
    "Brampton, ON – Rail service",
    "Brandon, MB",
    "Brantford, ON – Rail service",
    "Brochet, MB",
    "Brockville, ON",
    "Burns Lake, BC",
    "Calgary, AB",
    "Cambridge Bay, NU",
    "Campbell River, BC",
    "Campbellton, NB – Rail service",
    "Cape Dorset, NU",
    "Capreol, ON – Rail service",
    "Cartwright, NL",
    "Casselman, ON – Rail service",
    "Castlegar, BC",
    "Cat Lake, ON",
    "Chambord, QC – Rail service",
    "Chandler, QC – Rail service",
    "Chapleau, ON",
    "Charlottetown, NL",
    "Charlottetown, PE",
    "Chatham, ON",
    "Chemainus, BC – Rail service",
    "Chesterfield Inlet, NU",
    "Chevery, QC",
    "Chibougamau, QC",
    "Chisasibi, QC",
    "Churchill Falls, NL",
    "Churchill, MB – Rail service",
    "Churchill, MB",
    "Clyde River, NU",
    "Cobourg, ON – Rail service",
    "Colville Lake, NT",
    "Comox, BC",
    "Coral Harbour, NU",
    "Cornwall, ON",
    "Coteau, QC – Rail service",
    "Courtenay, BC",
    "Cranbrook, BC",
    "Cross Lake, MB",
    "Dauphin, MB",
    "Davis Inlet, NL",
    "Dawson City, YT",
    "Dawson Creek, BC",
    "Deer Lake, NL",
    "Deer Lake, ON",
    "Deline, NT",
    "Drummondville, QC – Rail service",
    "Dryden, ON",
    "Duncan/Quam, BC",
    "East Main, QC",
    "Edmonton, AB – Rail service",
    "Edmonton, AB – International",
    "Esquimalt, BC",
    "Flin Flon, MB",
    "Fond du Lac, SK",
    "Fort Albany, ON",
    "Fort Chipewyan, AB",
    "Fort Frances, ON",
    "Fort Good Hope, NT",
    "Fort Hope, ON",
    "Fort Mcmurray, AB",
    "Fort Nelson, BC",
    "Fort Severn, ON",
    "Fort Simpson, NT",
    "Fort Smith, NT",
    "Fort St John, BC",
    "Fox Harbour/St Lewis, NL",
    "Fredericton Junction, NB – Rail service",
    "Fredericton, NB",
    "Gander, NL",
    "Gaspe, QC – Rail service",
    "Gaspe, QC",
    "Georgetown, ON – Rail service",
    "Gethsemani, QC",
    "Gillam, MB",
    "Gillies Bay, BC",
    "Gjoa Haven, NU",
    "Glencoe, ON – Rail service",
    "Gods Narrows, MB",
    "Gods River, MB",
    "Goose Bay, NL",
    "Grande Prairie, AB",
    "Grimsby, ON",
    "Grise Fiord, NU",
    "Guelph, ON – Rail service",
    "Halifax, NS – Rail service",
    "Halifax, NS – International",
    "Hall Beach, NU",
    "Hamilton, ON",
    "Havre St Pierre, QC",
    "Hay River, NT",
    "Hervey, QC – Rail service",
    "High Level, AB",
    "Holman, NT",
    "Hopedale, NL",
    "Houston, BC – Bus station",
    "Hudson Bay, SK",
    "Igloolik, NU",
    "Iles De La Madeleine, QC",
    "Ilford, MB",
    "Ingersoll, ON – Rail service",
    "Inukjuak, QC",
    "Inuvik, NT",
    "Iqaluit, NU",
    "Island Lake/Garden Hill",
    "Ivujivik, QC",
    "Jasper, AB – Rail service",
    "Joliette, QC – Rail service",
    "Jonquiere, QC – Rail service",
    "Kamloops, BC",
    "Kangiqsualujjuaq, QC",
    "Kangiqsujuaq, QC",
    "Kangirsuk, QC",
    "Kapuskasing, ON",
    "Kasabonika, ON",
    "Kaschechewan, ON",
    "Keewaywin, ON",
    "Kegaska, QC",
    "Kelowna, BC",
    "Kenora, ON",
    "Kimmirut/Lake Harbour NU",
    "Kingfisher Lake, ON",
    "Kingston, ON – Rail service",
    "Kingston, ON – Norman Rogers Airport",
    "Kitchener, ON",
    "Klemtu, BC",
    "Kugaaruk, NU",
    "Kugluktuk/Coppermine, NU",
    "Kuujjuaq, QC",
    "Kuujjuarapik, QC",
    "La Grande, QC",
    "La Ronge, SK",
    "La Tabatiere, QC",
    "La Tuque, QC",
    "Lac Brochet, MB",
    "Lac Edouard, QC – Rail service",
    "Ladysmith, BC – Rail service",
    "Langford, BC – Rail service",
    "Lansdowne House, ON",
    "Leaf Rapids, MB",
    "Lethbridge, AB",
    "Lloydminister, AB",
    "London, ON – Rail service",
    "London, ON – Municipal Airport",
    "Lutselke/Snowdrift, NT",
    "Mary’s Harbour, NL",
    "Maxville, ON – Rail service",
    "Medicine Hat, AB",
    "Melville, SK – Rail service",
    "Miramichi, NB – Rail service",
    "Moncton, NB – Rail service",
    "Moncton, NB – Airport",
    "Mont Joli, QC",
    "Montreal, QC – Dorval Rail service",
    "Montreal, QC – Downtown Rail service",
    "Montreal, QC – St Lambert Rail service",
    "Montreal, QC – all airports",
    "Montreal, QC – Dorval",
    "Moosonee, ON",
    "Muskrat Dam, ON",
    "Nain, NL",
    "Nakina, ON",
    "Nanaimo, BC – Harbour Airport",
    "Nanaimo, BC – Cassidy Airport",
    "Nanisivik, NU",
    "Napanee, ON – Rail service",
    "Natashquan, QC",
    "Nemiscau, QC",
    "New Carlisle, QC – Rail service",
    "New Richmond, QC – Rail service",
    "Niagara Falls, ON – Rail service",
    "Noranda/Rouyn, QC",
    "Norman Wells, NT",
    "North Bay, ON",
    "North Spirit Lake, ON",
    "Norway House, MB",
    "Ogoki, ON",
    "Old Crow, YT",
    "Opapamiska Lake, ON",
    "Oshawa, ON",
    "Ottawa, ON – Rail service",
    "Ottawa, ON – International",
    "Oxford House, MB",
    "Pakuashipi, QC",
    "Pangnirtung, NU",
    "Parent, QC – Rail service",
    "Parksville, BC – Rail service",
    "Paulatuk, NT",
    "Peace River, AB",
    "Peawanuck, ON",
    "Pembroke, ON",
    "Penticton, BC",
    "Perce, QC – Rail service",
    "Pickle Lake, ON",
    "Pikangikum, ON",
    "Pointe-aux-Trembles, QC – Rail service",
    "Points North Landing, SK",
    "Pond Inlet, NU",
    "Poplar Hill, ON",
    "Port Alberni, BC",
    "Port Hardy, BC",
    "Port Hope Simpson, NL",
    "Port Meiner, QC",
    "Postville, NL",
    "Povungnituk, QC",
    "Powell River, BC",
    "Prescott, ON – Rail service",
    "Prince Albert, SK",
    "Prince George, BC – Rail service",
    "Prince George, BC",
    "Prince Rupert, BC – Rail service",
    "Prince Rupert, BC – Digby Island Airport",
    "Pukatawagan, MB –",
    "Qikiqtarjuaq, NU",
    "Qualicum, BC",
    "Quaqtaq, QC",
    "Quebec, QC – International Airport",
    "Quebec, QC – Charny Rail service",
    "Quebec, QC – Levis Rail service",
    "Quebec, QC – Quebec Station Rail service",
    "Quebec, QC – Sainte-Foy Rail service",
    "Quesnel, BC",
    "Rae Lakes, NT",
    "Rainbow Lake, AB",
    "Rankin Inlet, NU",
    "Red Lake, ON",
    "Red Sucker Lake, MB",
    "Regina, SK",
    "Repulse Bay, NU",
    "Resolute, NU",
    "Rigolet, NL",
    "Rimouski, QC",
    "Riviere-a-Pierre, QC – Rail service",
    "Roberval, QC",
    "Round Lake, ON",
    "Rouyn/Noranda, QC",
    "Sachigo Lake, ON",
    "Sachs Harbour, NT",
    "Sackville, NB – Rail service",
    "Saint Hyacinthe, QC – Rail service",
    "Saint John, NB",
    "Saint Johns, NL",
    "Saint Leonard, NB",
    "Salluit, QC",
    "Sandy Lake, ON",
    "Sanikiluaq, NU",
    "Sarnia, ON – Rail service",
    "Sarnia, ON",
    "Saskatoon, SK",
    "Sault Ste-Marie, ON",
    "Schefferville, QC",
    "Senneterre, QC – Rail service",
    "Sept-Iles, QC",
    "Shamattawa, MB",
    "Shawinigan, QC – Rail service",
    "Shawnigan, BC – Rail service",
    "Sioux Lookout, ON",
    "Smith Falls, ON",
    "Smithers, BC",
    "Snare Lake, NT",
    "South Indian Lake, MB",
    "St Anthony, NL",
    "St Catharines, ON",
    "St Marys, ON – Rail service",
    "Ste Therese Point, MB",
    "Stephenville, NL",
    "Stony Rapids, SK",
    "Strathroy, ON – Rail service",
    "Sudbury, ON – Rail service",
    "Sudbury, ON",
    "Summer Beaver, ON",
    "Swan River, MB",
    "Sydney, NS",
    "Tadoule Lake, MB",
    "Taloyoak, NU",
    "Tasiujuaq, QC",
    "Terrace, BC",
    "Tete-a-La Baleine, QC",
    "The Pas, MB – Rail service",
    "The Pas, MB",
    "Thicket Portage, MB",
    "Thompson, MB",
    "Thunder Bay, ON",
    "Timmins, ON",
    "Tofino, BC",
    "Toronto, ON – Downtown Rail service",
    "Toronto, ON – Guildwood Rail service",
    "Toronto, ON – Toronto Island Airport",
    "Toronto, ON – International",
    "Truro, NS – Rail service",
    "Tuktoyaktuk, NT",
    "Tulita/Fort Norman, NT",
    "Umiujag, QC",
    "Uranium City, SK",
    "Val-d’Or, QC",
    "Vancouver, BC – Coal Harbour",
    "Vancouver, BC – Rail service",
    "Vancouver, BC – International",
    "Victoria, BC – Inner Harbor",
    "Victoria, BC – International",
    "Wabush, NL",
    "Waskaganish, QC",
    "Watford, ON – Rail service",
    "Webequie, ON",
    "Wemindji, QC",
    "Weymont, QC – Rail service",
    "Wha Ti/Lac La Martre, NT",
    "Whale Cove, NU",
    "White River, ON",
    "Whitehorse, YT",
    "Williams Harbour, NL",
    "Williams Lake, BC",
    "Windsor, ON – Rail service",
    "Windsor, ON",
    "Winnipeg, MB – Rail service",
    "Winnipeg, MB – International",
    "Wollaston Lake, SK",
    "Woodstock, ON – Rail service",
    "Wunnummin Lake, ON",
    "Wyoming, ON – Rail service",
    "Yarmouth, NS",
    "Yellowknife, NT",
    "York Landing, MB"]

def airportSearch(str):
    retList = []
    length = len(str)
    for airport in locationsList:
        found = True
        if len(airport) < length: continue
        for i in range(length):
            if(airport[i] != str[i]):
                found = False
                break
        if(found): retList.append(airport)
    for airport in retList:
        print(airport)


airportSearch("Wi")